######################################################################
#
# File name : decoder_tb_wave.do
# Created on: Sat Oct 12 16:12:23 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
