######################################################################
#
# File name : DCPU_tb_simulate.do
# Created on: Tue Dec 16 12:33:54 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L dist_mem_gen_v8_0_10 -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.DCPU_tb xil_defaultlib.glbl

do {DCPU_tb_wave.do}

view wave
view structure
view signals

do {DCPU_tb.udo}

run 50000ns
