######################################################################
#
# File name : barrelshifter32_tb_wave.do
# Created on: Mon Oct 14 16:27:18 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
