######################################################################
#
# File name : logic_gates_tb.udo
# Created on: Sat Sep 21 20:20:52 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
