# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath D:/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/vivado_projects/encoder83/encoder83.cache/wt [current_project]
set_property parent.project_path D:/vivado_projects/encoder83/encoder83.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib D:/vivado_projects/encoder83/encoder83.srcs/sources_1/new/encoder83.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/desktop/encoder83.xdc
set_property used_in_implementation false [get_files D:/desktop/encoder83.xdc]


synth_design -top encoder83 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef encoder83.dcp

catch { report_utilization -file encoder83_utilization_synth.rpt -pb encoder83_utilization_synth.pb }
