######################################################################
#
# File name : _246tb_ex9_tb_compile.do
# Created on: Wed May 14 23:30:50 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/dist_mem_gen_v8_0_10
D:\\win32pe\\vlib msim/xil_defaultlib

D:\\win32pe\\vmap dist_mem_gen_v8_0_10 msim/dist_mem_gen_v8_0_10
D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\win32pe\\vlog -64 -incr -work dist_mem_gen_v8_0_10  \
"../../../CPU31.ip_user_files/ipstatic/dist_mem_gen_v8_0_10/simulation/dist_mem_gen_v8_0.v" \

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../CPU31.srcs/sources_1/ip/dist_mem_gen_0/sim/dist_mem_gen_0.v" \
"../../../CPU31.srcs/sources_1/new/RegFile.v" \
"../../../CPU31.srcs/sources_1/new/ALU.v" \
"../../../CPU31.srcs/sources_1/new/CU.v" \
"../../../CPU31.srcs/sources_1/new/PC.v" \
"../../../CPU31.srcs/sources_1/new/IMEM.v" \
"../../../CPU31.srcs/sources_1/new/DMEM.v" \
"../../../CPU31.srcs/sources_1/new/CPU.v" \
"../../../CPU31.srcs/sources_1/new/sccomp_dataflow.v" \
"../../../CPU31.srcs/sim_1/new/_246tb_ex9_tb.v" \

# compile glbl module
D:\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

