######################################################################
#
# File name : _246tb_ex9_tb_wave.do
# Created on: Wed May 14 22:30:14 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
