######################################################################
#
# File name : _246tb_ex7_tb_wave.do
# Created on: Fri Jul 11 00:11:23 +0800 2025
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
