######################################################################
#
# File name : pcreg_tb_wave.do
# Created on: Mon Oct 28 20:50:46 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
