######################################################################
#
# File name : pcreg_tb_compile.do
# Created on: Mon Oct 28 20:54:57 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/xil_defaultlib

D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../pcreg.srcs/sources_1/new/pcreg.v" \
"../../../pcreg.srcs/sim_1/new/pcreg_tb.v" \


# compile glbl module
D:\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

