# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath D:/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/vivado_projects/Asynchronous_D_FF/Asynchronous_D_FF.cache/wt [current_project]
set_property parent.project_path D:/vivado_projects/Asynchronous_D_FF/Asynchronous_D_FF.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib D:/vivado_projects/Asynchronous_D_FF/Asynchronous_D_FF.srcs/sources_1/new/Asynchronous_D_FF.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/desktop/D.xdc
set_property used_in_implementation false [get_files D:/desktop/D.xdc]


synth_design -top Asynchronous_D_FF -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Asynchronous_D_FF.dcp

catch { report_utilization -file Asynchronous_D_FF_utilization_synth.rpt -pb Asynchronous_D_FF_utilization_synth.pb }
