######################################################################
#
# File name : alu_tb_wave.do
# Created on: Tue Nov 12 09:29:47 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
