######################################################################
#
# File name : DIV_tb_wave.do
# Created on: Thu Apr 10 17:33:52 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
