######################################################################
#
# File name : DIV_tb_simulate.do
# Created on: Thu Apr 10 18:12:03 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.DIV_tb xil_defaultlib.glbl

do {DIV_tb_wave.do}

view wave
view structure
view signals

do {DIV_tb.udo}

run 2000ns
