# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath D:/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/vivado_projects/Counter8/Counter8.cache/wt [current_project]
set_property parent.project_path D:/vivado_projects/Counter8/Counter8.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/vivado_projects/JK_FF/JK_FF.srcs/sources_1/new/JK_FF.v
  D:/vivado_projects/display7/display7.srcs/sources_1/new/display7.v
  D:/vivado_projects/Counter8/Counter8.srcs/sources_1/new/Counter8.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/desktop/Counter8.xdc
set_property used_in_implementation false [get_files D:/desktop/Counter8.xdc]


synth_design -top Counter8 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Counter8.dcp

catch { report_utilization -file Counter8_utilization_synth.rpt -pb Counter8_utilization_synth.pb }
