######################################################################
#
# File name : MULT_tb_wave.do
# Created on: Thu Apr 03 19:40:31 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
