# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath D:/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/desktop/CPU31/CPU31.cache/wt [current_project]
set_property parent.project_path D:/desktop/CPU31/CPU31.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files D:/desktop/计组31指令CPU/31条指令CPU实验相关文档/31条CPUcoe文件/mips_31_mars_simulate.coe
add_files {{D:/desktop/计组31指令CPU/CPU31/Behavior Simulation/test_coe/1_addiu.coe}}
add_files {{D:/desktop/计组31指令CPU/CPU31/Behavior Simulation/test_coe/1_lui.coe}}
add_files {{D:/desktop/计组31指令CPU/CPU31/Behavior Simulation/test_coe/2_add.coe}}
add_files {{D:/desktop/计组31指令CPU/CPU31/Behavior Simulation/test_coe/2_addu.coe}}
add_files {{D:/desktop/Mars4_5 导出十六进制文件及结果比对说明/addi.coe}}
add_files {{D:/desktop/计组31指令CPU/CPU31/Behavior Simulation/test_coe/3.5_bne.coe}}
add_files {{D:/desktop/计组31指令CPU/CPU31/Behavior Simulation/test_coe/3.5_beq.coe}}
add_files {{D:/desktop/计组31指令CPU/CPU31/Behavior Simulation/test_coe/2_srav.coe}}
add_files {{D:/desktop/计组31指令CPU/CPU31/Behavior Simulation/test_coe/2_lwsw.coe}}
add_files {{D:/desktop/Mars4_5 导出十六进制文件及结果比对说明/lwsw.coe}}
add_files {{D:/desktop/计组31指令CPU/CPU31/Behavior Simulation/test_coe/2_lwsw2.coe}}
add_files {{D:/desktop/计组31指令CPU/CPU31/Behavior Simulation/test_coe/2_slt.coe}}
add_files D:/desktop/计组31指令CPU/31条指令CPU实验相关文档/31条CPUcoe文件/mips_31_mars_board_switch.coe
add_files -quiet d:/desktop/CPU31/CPU31.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp
set_property used_in_implementation false [get_files d:/desktop/CPU31/CPU31.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp]
read_verilog -library xil_defaultlib {
  D:/desktop/CPU31/CPU31.srcs/sources_1/new/RegFile.v
  D:/desktop/CPU31/CPU31.srcs/sources_1/new/ALU.v
  D:/desktop/CPU31/CPU31.srcs/sources_1/new/CU.v
  D:/desktop/CPU31/CPU31.srcs/sources_1/new/PC.v
  D:/desktop/CPU31/CPU31.srcs/sources_1/new/IMEM.v
  D:/desktop/CPU31/CPU31.srcs/sources_1/new/DMEM.v
  D:/desktop/CPU31/CPU31.srcs/sources_1/new/CPU.v
  D:/desktop/计组31指令CPU/31条指令CPU实验相关文档/31条CPU后仿真和下板说明/seg7x16.v
  D:/desktop/计组31指令CPU/CPU31/source/Divider.v
  D:/desktop/CPU31/CPU31.srcs/sources_1/new/sccomp_dataflow.v
  D:/desktop/CPU31/CPU31.srcs/sources_1/new/top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/desktop/CPU31/CPU31.srcs/constrs_1/new/cpu31.xdc
set_property used_in_implementation false [get_files D:/desktop/CPU31/CPU31.srcs/constrs_1/new/cpu31.xdc]

read_xdc D:/desktop/计组31指令CPU/31条指令CPU实验相关文档/31条CPU后仿真和下板说明/icf.xdc
set_property used_in_implementation false [get_files D:/desktop/计组31指令CPU/31条指令CPU实验相关文档/31条CPU后仿真和下板说明/icf.xdc]


synth_design -top top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
