######################################################################
#
# File name : Regfiles_tb_wave.do
# Created on: Sat Nov 23 00:37:09 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
