######################################################################
#
# File name : Regfiles_tb_compile.do
# Created on: Sat Nov 23 00:52:57 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/xil_defaultlib

D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../Regfiles.srcs/sources_1/new/Regfiles.v" \
"../../../Regfiles.srcs/sim_1/new/Regfiles_tb.v" \


# compile glbl module
D:\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

