######################################################################
#
# File name : extend_tb_wave.do
# Created on: Sat Sep 21 22:01:12 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
