######################################################################
#
# File name : de_selector14_tb_wave.do
# Created on: Mon Sep 30 19:27:43 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
