######################################################################
#
# File name : DMUX_tb.udo
# Created on: Mon Sep 30 16:25:50 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
