######################################################################
#
# File name : ram_tb_simulate.do
# Created on: Fri Nov 22 22:38:24 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.ram_tb xil_defaultlib.glbl

do {ram_tb_wave.do}

view wave
view structure
view signals

do {ram_tb.udo}

run 1000ns
