######################################################################
#
# File name : ram_tb_wave.do
# Created on: Mon Nov 18 16:20:32 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
