######################################################################
#
# File name : Adder_tb_wave.do
# Created on: Mon Oct 21 17:13:57 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
