######################################################################
#
# File name : Adder_tb_compile.do
# Created on: Mon Oct 21 17:18:24 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/xil_defaultlib

D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../../FA/FA.srcs/sources_1/new/FA.v" \
"../../../Adder.srcs/sources_1/new/Adder.v" \
"../../../Adder.srcs/sim_1/new/Adder_tb.v" \


# compile glbl module
D:\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

