######################################################################
#
# File name : DCPU_tb_wave.do
# Created on: Tue Dec 16 18:24:42 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
