######################################################################
#
# File name : top_board_wave.do
# Created on: Tue Dec 16 18:15:18 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
