######################################################################
#
# File name : top_board_simulate.do
# Created on: Tue Dec 16 18:15:18 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L dist_mem_gen_v8_0_10 -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.top_board xil_defaultlib.glbl

do {top_board_wave.do}

view wave
view structure
view signals

do {top_board.udo}

run 50000ns
