######################################################################
#
# File name : logic_gates_2_wave.do
# Created on: Sat Sep 21 21:02:19 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
