######################################################################
#
# File name : logic_gates_tb_compile.do
# Created on: Sat Sep 21 21:06:23 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/xil_defaultlib

D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../logic_gates_2.srcs/sources_1/new/logic_gates_2.v" \
"../../../logic_gates_2.srcs/sim_1/new/logic_gates_2_tb.v" \


# compile glbl module
D:\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

