######################################################################
#
# File name : logic_gates_tb.udo
# Created on: Sat Sep 21 21:05:08 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
