######################################################################
#
# File name : logic_gates_2_simulate.do
# Created on: Sat Sep 21 21:02:19 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.logic_gates_2 xil_defaultlib.glbl

do {logic_gates_2_wave.do}

view wave
view structure
view signals

do {logic_gates_2.udo}

run 1000ns
