######################################################################
#
# File name : logic_gates_2_tb.udo
# Created on: Sat Sep 21 21:03:31 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
