######################################################################
#
# File name : ram2_tb.udo
# Created on: Mon Nov 18 17:16:51 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
