######################################################################
#
# File name : ram2_tb_wave.do
# Created on: Mon Nov 18 17:16:51 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
