######################################################################
#
# File name : three_state_gates.udo
# Created on: Sat Sep 21 21:46:44 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
