######################################################################
#
# File name : three_state_gates_simulate.do
# Created on: Sat Sep 21 21:46:44 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.three_state_gates xil_defaultlib.glbl

do {three_state_gates_wave.do}

view wave
view structure
view signals

do {three_state_gates.udo}

run 1000ns
