######################################################################
#
# File name : three_state_gates_tb.udo
# Created on: Sat Sep 21 21:53:44 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
