######################################################################
#
# File name : three_state_gates_wave.do
# Created on: Sat Sep 21 21:46:44 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
