######################################################################
#
# File name : PCPU_tb_simple_debug_simulate.do
# Created on: Tue Nov 11 09:57:30 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L dist_mem_gen_v8_0_10 -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.PCPU_tb_simple_debug xil_defaultlib.glbl

do {PCPU_tb_simple_debug_wave.do}

view wave
view structure
view signals

do {PCPU_tb_simple_debug.udo}

run 2000ns
