######################################################################
#
# File name : PCPU_simulate.do
# Created on: Sat Nov 15 11:43:02 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L dist_mem_gen_v8_0_10 -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.PCPU xil_defaultlib.glbl

do {PCPU_wave.do}

view wave
view structure
view signals

do {PCPU.udo}

run 2000ns
