######################################################################
#
# File name : PCPU_wave.do
# Created on: Sat Nov 15 11:43:02 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
