######################################################################
#
# File name : PCPU_tb_drop_eggs_compile.do
# Created on: Wed Dec 24 09:21:21 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/dist_mem_gen_v8_0_10
D:\\win32pe\\vlib msim/xil_defaultlib

D:\\win32pe\\vmap dist_mem_gen_v8_0_10 msim/dist_mem_gen_v8_0_10
D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\win32pe\\vlog -64 -incr -work dist_mem_gen_v8_0_10  \
"../../../PCPU.ip_user_files/ipstatic/dist_mem_gen_v8_0_10/simulation/dist_mem_gen_v8_0.v" \

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../PCPU.srcs/sources_1/ip/dist_mem_gen_0/sim/dist_mem_gen_0.v" \
"../../../PCPU.srcs/sources_1/new/Regfile.v" \
"../../../PCPU.srcs/sources_1/new/Hazard_Unit.v" \
"../../../PCPU.srcs/sources_1/new/ALU.v" \
"../../../PCPU.srcs/sources_1/new/IMEM.v" \
"../../../PCPU.srcs/sources_1/new/DMEM.v" \
"../../../PCPU.srcs/sources_1/new/PCPU.v" \
"../../../PCPU.srcs/sim_1/new/PCPU_tb.v" \

# compile glbl module
D:\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

