######################################################################
#
# File name : PCPU_tb_drop_eggs_simulate.do
# Created on: Wed Dec 24 09:21:32 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L dist_mem_gen_v8_0_10 -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.PCPU_tb_drop_eggs xil_defaultlib.glbl

do {PCPU_tb_drop_eggs_wave.do}

view wave
view structure
view signals

do {PCPU_tb_drop_eggs.udo}

run 2000ns
