######################################################################
#
# File name : PCPU_tb_simple_debug_wave.do
# Created on: Tue Nov 11 09:57:30 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
