######################################################################
#
# File name : PCPU_tb_wave.do
# Created on: Tue Nov 11 10:39:55 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
