######################################################################
#
# File name : simple_debug_tb.udo
# Created on: Mon Nov 10 19:18:28 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
