######################################################################
#
# File name : PCPU_tb_drop_eggs_wave.do
# Created on: Sat Nov 15 16:22:01 +0800 2025
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
