######################################################################
#
# File name : PCPU_tb_drop_eggs_simulate.do
# Created on: Sat Nov 15 16:56:26 +0800 2025
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vsim -voptargs="+acc" +transport_int_delays +pulse_r/0 +pulse_int_r/0 -L simprims_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.PCPU_tb_drop_eggs xil_defaultlib.glbl

do {PCPU_tb_drop_eggs_wave.do}

view wave
view structure
view signals

do {PCPU_tb_drop_eggs.udo}

run 2000ns
