######################################################################
#
# File name : PCPU_tb_drop_eggs_compile.do
# Created on: Sat Nov 15 16:56:17 +0800 2025
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/xil_defaultlib

D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"PCPU_tb_drop_eggs_time_synth.v" \
"../../../../PCPU.srcs/sim_1/new/PCPU_tb.v" \


quit -force

