######################################################################
#
# File name : _246tb_ex7_tb_wave.do
# Created on: Wed Jul 09 18:24:54 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
