######################################################################
#
# File name : _246tb_ex7_tb_simulate.do
# Created on: Thu Jul 10 23:49:23 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L dist_mem_gen_v8_0_10 -L xil_defaultlib -lib xil_defaultlib xil_defaultlib._246tb_ex7_tb xil_defaultlib.glbl

do {_246tb_ex7_tb_wave.do}

view wave
view structure
view signals

do {_246tb_ex7_tb.udo}

run 500000ns
