create_clock -period 10.000 -name clk_pin -waveform {0.000 5.000} [get_ports clk_in]
set_input_delay -clock [get_clocks clk_pin] 0.000 [get_ports reset]
set_output_delay -clock [get_clocks clk_pin] 0.000 [get_ports -filter { NAME =~  "*" && DIRECTION == "OUT" }]
create_clock -period 12.000 -name clk_pin -waveform {0.000 6.000} [get_ports clk_in]
create_clock -period 11.000 -name clk_pin -waveform {0.000 5.500} [get_ports clk_in]
set_input_delay -clock [get_clocks clk_pin] 1.000 [get_ports reset]
set_output_delay -clock [get_clocks clk_pin] 1.000 [get_ports -filter { NAME =~  "*" && DIRECTION == "OUT" }]
set_output_delay -clock [get_clocks clk_pin] 0.000 [get_ports -filter { NAME =~  "*" && DIRECTION == "OUT" }]
set_output_delay -clock [get_clocks clk_pin] 0.000 [get_ports -filter { NAME =~  "*" && DIRECTION == "OUT" }]
