######################################################################
#
# File name : _246tb_ex9_tb_wave.do
# Created on: Sun May 18 22:40:19 +0800 2025
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
