######################################################################
#
# File name : _246tb_ex9_tb_compile.do
# Created on: Sun May 18 22:58:36 +0800 2025
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/xil_defaultlib

D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"_246tb_ex9_tb_time_synth.v" \
"../../../../CPU31.srcs/sim_1/new/_246tb_ex9_tb.v" \


quit -force

