# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath D:/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/vivado_projects/PCPU/PCPU.cache/wt [current_project]
set_property parent.project_path D:/vivado_projects/PCPU/PCPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files D:/vivado_projects/PCPU/cross_verify_pcpu.coe
add_files D:/vivado_projects/PCPU/drop_eggs.coe
add_files -quiet d:/vivado_projects/PCPU/PCPU.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp
set_property used_in_implementation false [get_files d:/vivado_projects/PCPU/PCPU.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp]
read_verilog -library xil_defaultlib {
  D:/vivado_projects/PCPU/PCPU.srcs/sources_1/new/Regfile.v
  D:/vivado_projects/PCPU/PCPU.srcs/sources_1/new/Hazard_Unit.v
  D:/vivado_projects/PCPU/PCPU.srcs/sources_1/new/ALU.v
  D:/vivado_projects/PCPU/PCPU.srcs/sources_1/new/IMEM.v
  D:/vivado_projects/PCPU/PCPU.srcs/sources_1/new/DMEM.v
  D:/vivado_projects/PCPU/PCPU.srcs/sources_1/new/Divider.v
  D:/vivado_projects/PCPU/PCPU.srcs/sources_1/new/seg7x16.v
  D:/vivado_projects/PCPU/PCPU.srcs/sources_1/new/PCPU.v
  D:/vivado_projects/PCPU/PCPU.srcs/sources_1/new/top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivado_projects/PCPU/PCPU.srcs/sources_1/new/icf.xdc
set_property used_in_implementation false [get_files D:/vivado_projects/PCPU/PCPU.srcs/sources_1/new/icf.xdc]


synth_design -top top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
