# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/vivado_projects/DCPU1/DCPU1.runs/synth_1/.Xil/Vivado-25656-LAPTOP-V0AHCU9H/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tcsg324-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -include d:/vivado_projects/DCPU1/DCPU1.srcs/sources_1/ip/dist_mem_gen_0 {
      D:/vivado_projects/DCPU1/DCPU1.srcs/sources_1/new/Controller.v
      D:/vivado_projects/DCPU1/DCPU1.srcs/sources_1/new/IMEM.v
      D:/vivado_projects/DCPU1/DCPU1.srcs/sources_1/new/HazardUnit.v
      D:/vivado_projects/DCPU1/DCPU1.srcs/sources_1/new/ForwardUnit.v
      D:/vivado_projects/DCPU1/DCPU1.srcs/sources_1/new/DMEM.v
      D:/vivado_projects/DCPU1/DCPU1.srcs/sources_1/new/MDU.v
      D:/vivado_projects/DCPU1/DCPU1.srcs/sources_1/new/ALU.v
      D:/vivado_projects/DCPU1/DCPU1.srcs/sources_1/new/RegFile.v
      D:/vivado_projects/DCPU1/DCPU1.srcs/sources_1/new/CP0.v
      D:/vivado_projects/DCPU1/DCPU1.srcs/sources_1/new/seg7x16.v
      D:/vivado_projects/DCPU1/DCPU1.srcs/sources_1/new/Divider.v
      D:/vivado_projects/DCPU1/DCPU1.srcs/sources_1/new/DCPU.v
      D:/vivado_projects/DCPU1/DCPU1.srcs/sources_1/new/top_borad.v
    }
      rt::read_vhdl -lib dist_mem_gen_v8_0_10 {
      d:/vivado_projects/DCPU1/DCPU1.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_v8_0_10/hdl/dist_mem_gen_v8_0_vhsyn_rfs.vhd
      d:/vivado_projects/DCPU1/DCPU1.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_v8_0_10/hdl/dist_mem_gen_v8_0.vhd
    }
      rt::read_vhdl -lib xil_defaultlib d:/vivado_projects/DCPU1/DCPU1.srcs/sources_1/ip/dist_mem_gen_0/synth/dist_mem_gen_0.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top_board
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "D:/vivado_projects/DCPU1/DCPU1.runs/synth_1/.Xil/Vivado-25656-LAPTOP-V0AHCU9H/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
      rt::run_rtlelab -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
