######################################################################
#
# File name : data_selecter41_tb_wave.do
# Created on: Sun Sep 29 15:52:21 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
