######################################################################
#
# File name : encoder83_tb_wave.do
# Created on: Sat Oct 12 17:11:00 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
