######################################################################
#
# File name : encoder83_tb.udo
# Created on: Sat Oct 12 17:11:00 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
