######################################################################
#
# File name : Divider_tb_wave.do
# Created on: Mon Nov 04 17:15:50 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
