######################################################################
#
# File name : logic_gates_tb.udo
# Created on: Fri Sep 20 18:12:20 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
