######################################################################
#
# File name : logic_gates_tb_wave.do
# Created on: Fri Sep 20 18:12:20 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
