######################################################################
#
# File name : display7_tb_wave.do
# Created on: Sat Oct 12 16:50:40 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
