######################################################################
#
# File name : DCPU_tb_compile.do
# Created on: Mon Dec 15 21:16:43 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/dist_mem_gen_v8_0_10
D:\\win32pe\\vlib msim/xil_defaultlib

D:\\win32pe\\vmap dist_mem_gen_v8_0_10 msim/dist_mem_gen_v8_0_10
D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\win32pe\\vlog -64 -incr -work dist_mem_gen_v8_0_10  \
"../../../DCPU.ip_user_files/ipstatic/dist_mem_gen_v8_0_10/simulation/dist_mem_gen_v8_0.v" \

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../DCPU.srcs/sources_1/ip/dist_mem_gen_0/sim/dist_mem_gen_0.v" \
"../../../DCPU.srcs/sources_1/new/CP0.v" \
"../../../DCPU.srcs/sources_1/new/RegFile.v" \
"../../../DCPU.srcs/sources_1/new/MDU.v" \
"../../../DCPU.srcs/sources_1/new/HazardUnit.v" \
"../../../DCPU.srcs/sources_1/new/ForwardUnit.v" \
"../../../DCPU.srcs/sources_1/new/DMEM.v" \
"../../../DCPU.srcs/sources_1/new/Controller.v" \
"../../../DCPU.srcs/sources_1/new/ALU.v" \
"../../../DCPU.srcs/sources_1/new/IMEM.v" \
"../../../DCPU.srcs/sources_1/new/DCPU.v" \
"../../../DCPU.srcs/sim_1/new/DCPU_tb.v" \

# compile glbl module
D:\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

