######################################################################
#
# File name : DCPU_tb_wave.do
# Created on: Mon Dec 08 20:59:04 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
