# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath D:/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/vivado_projects/DCPU2/DCPU2.cache/wt [current_project]
set_property parent.project_path D:/vivado_projects/DCPU2/DCPU2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files D:/desktop/verify_optimized3.coe
read_ip -quiet D:/vivado_projects/DCPU2/DCPU2.srcs/sources_1/ip/dist_mem_gen_0_1/dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/vivado_projects/DCPU2/DCPU2.srcs/sources_1/ip/dist_mem_gen_0_1/dist_mem_gen_0_ooc.xdc]
set_property is_locked true [get_files D:/vivado_projects/DCPU2/DCPU2.srcs/sources_1/ip/dist_mem_gen_0_1/dist_mem_gen_0.xci]

read_verilog -library xil_defaultlib {
  D:/vivado_projects/DCPU2/DCPU2.srcs/sources_1/new/IMEM.v
  D:/vivado_projects/DCPU2/DCPU2.srcs/sources_1/new/RegFile.v
  D:/vivado_projects/DCPU2/DCPU2.srcs/sources_1/new/HazardUnit.v
  D:/vivado_projects/DCPU2/DCPU2.srcs/sources_1/new/DMEM.v
  D:/vivado_projects/DCPU2/DCPU2.srcs/sources_1/new/MDU.v
  D:/vivado_projects/DCPU2/DCPU2.srcs/sources_1/new/Controller.v
  D:/vivado_projects/DCPU2/DCPU2.srcs/sources_1/new/CP0.v
  D:/vivado_projects/DCPU2/DCPU2.srcs/sources_1/new/ForwardUnit.v
  D:/vivado_projects/DCPU2/DCPU2.srcs/sources_1/new/ALU.v
  D:/vivado_projects/DCPU2/DCPU2.srcs/sources_1/new/Divider.v
  D:/vivado_projects/DCPU2/DCPU2.srcs/sources_1/new/DCPU.v
  D:/vivado_projects/DCPU2/DCPU2.srcs/sources_1/new/seg7x16.v
  D:/vivado_projects/DCPU2/DCPU2.srcs/sources_1/new/top_borad.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivado_projects/DCPU2/DCPU2.srcs/constrs_1/new/DCPU.xdc
set_property used_in_implementation false [get_files D:/vivado_projects/DCPU2/DCPU2.srcs/constrs_1/new/DCPU.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top_board -part xc7a100tcsg324-1 -max_dsp 0


write_checkpoint -force -noxdef top_board.dcp

catch { report_utilization -file top_board_utilization_synth.rpt -pb top_board_utilization_synth.pb }
