######################################################################
#
# File name : CPO_tb_compile.do
# Created on: Sun Jun 15 11:34:26 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/xil_defaultlib

D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../CP0.srcs/sources_1/new/CP0.v" \
"../../../CP0.srcs/sim_1/new/CP0_tb.v" \


# compile glbl module
D:\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

