######################################################################
#
# File name : CPO_tb.udo
# Created on: Sun Jun 15 11:07:53 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
