######################################################################
#
# File name : CPO_tb_simulate.do
# Created on: Sun Jun 15 11:34:32 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.CPO_tb xil_defaultlib.glbl

do {CPO_tb_wave.do}

view wave
view structure
view signals

do {CPO_tb.udo}

run 1000ns
