######################################################################
#
# File name : CPO_tb_wave.do
# Created on: Sun Jun 15 11:07:53 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
