# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath D:/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/vivado_projects/three_state_gates/three_state_gates.cache/wt [current_project]
set_property parent.project_path D:/vivado_projects/three_state_gates/three_state_gates.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib D:/vivado_projects/three_state_gates/three_state_gates.srcs/sources_1/new/three_state_gates.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivado_projects/three_state_gates/three_state_gates.srcs/constrs_1/new/three_state_gates_xdc.xdc
set_property used_in_implementation false [get_files D:/vivado_projects/three_state_gates/three_state_gates.srcs/constrs_1/new/three_state_gates_xdc.xdc]


synth_design -top three_state_gates -part xc7a100tcsg324-1


write_checkpoint -force -noxdef three_state_gates.dcp

catch { report_utilization -file three_state_gates_utilization_synth.rpt -pb three_state_gates_utilization_synth.pb }
