######################################################################
#
# File name : MULTU_tb_wave.do
# Created on: Wed Apr 02 08:51:49 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
