######################################################################
#
# File name : MULTU_tb_simulate.do
# Created on: Thu Apr 03 17:57:31 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.MULTU_tb xil_defaultlib.glbl

do {MULTU_tb_wave.do}

view wave
view structure
view signals

do {MULTU_tb.udo}

run 1000ns
