######################################################################
#
# File name : transmission8_tb_wave.do
# Created on: Mon Sep 30 17:26:06 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
