######################################################################
#
# File name : transmission8_tb_compile.do
# Created on: Mon Sep 30 19:41:25 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/xil_defaultlib

D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../transmission8.srcs/sources_1/new/transmission8.v" \
"../../../transmission8.srcs/sim_1/new/transmission8_tb.v" \


# compile glbl module
D:\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

