######################################################################
#
# File name : transmission8_tb_simulate.do
# Created on: Mon Sep 30 19:41:29 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.transmission8_tb xil_defaultlib.glbl

do {transmission8_tb_wave.do}

view wave
view structure
view signals

do {transmission8_tb.udo}

run 1000ns
