######################################################################
#
# File name : encoder83_Pri_tb.udo
# Created on: Sat Oct 12 17:50:54 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
