######################################################################
#
# File name : encoder83_Pri_tb_compile.do
# Created on: Sat Oct 12 17:50:48 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/xil_defaultlib

D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../encoder83_Pri.srcs/sources_1/new/encoder83_Pri.v" \
"../../../encoder83_Pri.srcs/sim_1/new/encoder83_Pri_tb.v" \


# compile glbl module
D:\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

